name: e_commerce
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8

  # State Management
  get: ^4.7.2
  http: ^1.5.0
  intl: ^0.20.2
  logger: ^2.6.2
  url_launcher: ^6.3.2
  get_storage: ^2.1.1
  flutter_native_splash: ^2.4.7
  smooth_page_indicator: ^1.2.1
  carousel_slider: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  #------------------ LOCAL ASSETS ------------------#
  assets:
    - assets/logo/
    - assets/icons/brands/
    - assets/icons/categories/
    - assets/images/banners/
    - assets/images/on_boarding_images/
    - assets/images/animations/

  #------------------ LOCAL FONTS ------------------#
  fonts:
    - family: Coolvetica
      fonts:
        - asset: assets/fonts/coolvetica_regular.otf
          weight: 400
        - asset: assets/fonts/coolvetica_regular_italic.otf
          style: italic

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
 
