// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKCNuCa898SrRzLHJdj-FVhA2qZct-qUQ',
    appId: '1:324918961275:web:ce39e561e68f01c4baaede',
    messagingSenderId: '324918961275',
    projectId: 'ecommerce-11ac5',
    authDomain: 'ecommerce-11ac5.firebaseapp.com',
    storageBucket: 'ecommerce-11ac5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEIRlGWv_E5rEy4TgDstlk9CeRoGyayGE',
    appId: '1:324918961275:android:be4626e77fda65ffbaaede',
    messagingSenderId: '324918961275',
    projectId: 'ecommerce-11ac5',
    storageBucket: 'ecommerce-11ac5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx-zRvLZbWq5is-QR0f9Au9q1y7hEF3Yg',
    appId: '1:324918961275:ios:b8beeb2a5ea34ec9baaede',
    messagingSenderId: '324918961275',
    projectId: 'ecommerce-11ac5',
    storageBucket: 'ecommerce-11ac5.firebasestorage.app',
    androidClientId: '324918961275-9hkn7banrf0cn071j0uvdhv3gjpouvh7.apps.googleusercontent.com',
    iosClientId: '324918961275-f8i3hgl53ehn34rbglofvpkfbj1dnb41.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );

}